# Generated by Django 6.0.4 on 2026-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fujiyama_club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт (лет)')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
