# Generated by Django 6.0.4 on 2026-07-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fujiyama_club', '0003_coach_limit_to_staff'),
        ('fujiyama_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_requests', to='fujiyama_club.traininggroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Заявка на запись',
                'verbose_name_plural': 'Заявки на запись',
                'ordering': ['-created_at'],
            },
        ),
    ]
